NPM = npm

build-RegisterUserFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-GetUserProfileFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-GetUserSessionsFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-CreateGameSessionFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-RequestHintFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-SubmitAnswerFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-EndGameSessionFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-GetSolutionExplanationFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-GetLeaderboardFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-GetActivityStatsFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-UpdatePublicStatsCacheFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production

build-GetGameSessionFunction:
	$(NPM) install
	$(NPM) run build
	cp -r dist/* $(ARTIFACTS_DIR)/
	cp package*.json $(ARTIFACTS_DIR)/
	cd $(ARTIFACTS_DIR) && $(NPM) install --production
